name: npm-publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 19
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Test
        run: npm test
      
      - name: Semantic Release
        uses: codfish/semantic-release-action@v2
        with:
          branches: "main"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          
      - name: Display Release Version
        run: echo ${{ steps.semantic.outputs.release-version }}

      - name: Displsy Semantic Release Outputs
        run: echo "$OUTPUTS"
        env:
          OUTPUTS: ${{ toJson(steps.semantic.outputs) }}
