name: npm-publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 19

      - name: Install dependencies
        run: npm ci

      - name: Test
        run: npm test

      - name: Bump version, generate changelog, and cut release
        run: npx standard-version --release-as ${GITHUB_REF#refs/tags/v} --tag-prefix v --infile CHANGELOG.md --commit-all --skip.changelog

      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
